version: "3.8"

services:
#  app:
#    build:
#      context: .
#      target: runner
#    container_name: bank-account-management
#    ports:
#      - "8090:8090"
#    environment:
#      MICRONAUT_ENVIRONMENTS: dev
#      AWS_ACCESS_KEY_ID: test
#      AWS_SECRET_ACCESS_KEY: test
#      AWS_DEFAULT_REGION: us-east-1
#      AWS_DYNAMODB_ENDPOINT: http://localstack:4566
#      AWS_SNS_ENDPOINT: http://localstack:4566
#      AWS_DYNAMODB_BANKING_ENTITIES_TABLE_NAME: banking-entities
#      AWS_SNS_ACCOUNT_HOLDER_CREATED_TOPIC_ARN: arn:aws:sns:us-east-1:000000000000:account-holder-created
#    networks:
#      - bank_account_management
#    depends_on:
#      - localstack

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:3.7.0
    ports:
      - '127.0.0.1:4566:4566'
    environment:
      SERVICES: dynamodb, sns
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
      LS_LOG: ${LS_LOG:-debug}
    networks:
      - bank_account_management
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./localstack:/etc/localstack/init/ready.d

  redis:
    image: redis:7.4.3
    container_name: bank-accounts-redis-7.4.3
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - bank_account_redis_data:/data
    networks:
      - bank_account_management
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping || exit 1" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

volumes:
  bank_account_redis_data:
    name: bank-account-management-redis-data
networks:
  bank_account_management:
    name: bank-account-management-network