spring:
  application:
    name: bank-account-management

server:
  port: 8090

aws:
  region: ${AWS_DEFAULT_REGION}
  dynamodb:
    tables:
      banking-entities:
        table-name: ${AWS_DYNAMODB_BANKING_ENTITIES_TABLE_NAME}
  sns:
    topics:
      account-holder-created:
        topic-arn: ${AWS_SNS_ACCOUNT_HOLDER_CREATED_TOPIC_ARN}

api:
  v1:
    root-path: '/api/v1/bank-accounts'
    bank-account-path: '/api/v1/bank-accounts/{bank-account-id}'
    account-holders-path: '/api/v1/bank-accounts/{bank-account-id}/account-holders'
    account-holder-path: '/api/v1/bank-accounts/{bank-account-id}/account-holders/{account-holder-id}'

caches:
  bank-accounts-by-id:
    name: 'bank-accounts-by-id'

#api:
#  v1:
#    base-path: '/api/v1'
#    bank-accounts:
#      root-path: '/bank-accounts'
#      by-id-path: '/bank-accounts/{bank-account-id}'
#      by-iban-path: '/bank-accounts/iban/{iban}'
#      account-holders-path: '/bank-accounts/{bank-account-id}/account-holders'
